title:            XIE Yuheng
description:      "personal web site of XIE Yuheng"

host: 0.0.0.0
port: 4444
baseurl: ""

url: "http://xieyuheng.github.io"

owner:
  name:           XIE Yuheng
  email:          xyheme@gmail.com

timezone:    Asia/Shanghai
future:      true

exclude: ["makefile", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]



url: "http://0.0.0.0:4444"